version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    working_directory: ~/OpenAPITools/openapi-generator
    parallelism: 1
    shell: /bin/bash --login
    steps:
    - run: "To avoid build failure due to missing circle.yml"
